### PR TITLE
ADMINUI-2083 self-signed cert should not be SHA-1

### PR DESCRIPTION
**Pull request by dan-luk**

### CODE REVIEW

**Comment by trentm** [comment]
Sorry to jump in, but where does this change anything from SHA-1? There is this: https://github.com/joyent/sdc-adminui/blob/master/boot/setup.sh#L29-L35  which AFAICT is the same as this tools/ssl.sh

**Comment by dan-luk** [comment]
that was cool jump, Trent :)

**Comment by lloydde** [comment]
@dan-luk should the Makefile just call "boot/setup.sh" with a parameter to override the output directory? Or some other approach that doesn't duplicate the cert generation in two places.

(Squash commits as well.)

**Comment by trentm** [comment]
Is there a need for a separate scirpt or Makefile task? Perhaps just this change:

```
diff --git a/boot/setup.sh b/boot/setup.sh
index a598364..65ece44 100755
--- a/boot/setup.sh
+++ b/boot/setup.sh
@@ -30,7 +30,7 @@ mkdir -p /opt/smartdc/adminui
 mkdir -p /opt/smartdc/adminui/etc/ssl
 echo "Generating SSL Certificate"
 /opt/local/bin/openssl req -x509 -nodes -subj '/CN=*' \
-    -newkey rsa:4096 -days 365 \
+    -newkey rsa:4096 -sha256 -days 365 \
     -keyout /opt/smartdc/adminui/etc/ssl/default.pem \
     -out /opt/smartdc/adminui/etc/ssl/default.pem
 

```

**Comment by lloydde** [comment]
@trentm maybe not, the other part is now trumped by [ADMINUI-2126 - doc development of adminui on coal](https://smartos.org/bugview/ADMINUI-2126).

**Comment by lloydde** [comment]
I just took the boot/setup.sh change for now, b52fd3a5267e719c6948b5210e5eeca9dd1cc031.

**Pull request closed without merging**
