### PR TITLE
ADMINUI-2160 add ip addresses to network

### PR DESCRIPTION
**Pull request by andyYatskov**

### CODE REVIEW

**Comment by YZaicev** [comment]
need add pagination on the addresses list

**Comment by YZaicev** [comment]
:ok: :1234:

**Comment by askfongjojo** [comment]
Hi @andyYatskov - Add IP address works out pretty well. But the select range does not appear to work for the "Reserve" action now that we have pagination. When I select with "Select Range" and then click "Reserve" in the blue bar at the bottom, even though it shows the correct number of records selected and gives me the popup to confirm reservation, the action doesn't actually take place. If I use the header-level checkbox to select all records on the page and click "Reserve" in the blue bar, that's when the reserve action would happen. Can you please check if we can fix this? I am fine with limiting user to reserve up to a certain number of IP at a time, if it makes implementation cleaner/easier. The network I used to replicate the above issue is  10.1.0.0/19, with a provisionable range of 10.12.1.5 - 10.12.1.254.

**Comment by askfongjojo** [comment]
Hi @andyYatskov, the fix is good. I did however found another issue with pagination across all IP addresses from the database. NAPI currently returns only up to 1000 records in each call. We'll need to have logic to set offset and limit to retrieve all the records of networks that have >1000 IP addresses. For example, to see the 1001st-1050th IP addresses, the NAPI call will have to be:
$ sdc-napi /networks/:uuid/ips?offset=1000\&limit=50

Using the same network I have above (10.1.0.0/19), there could be up to a few thousand IP addresses. AdminUI will have to do the API multiple times till there is no more address returned.

**Comment by askfongjojo** [comment]
Merged as cefd531

**Pull request closed without merging**
