### PR TITLE
ADMINUI-2134 fabric network creation box should fill in unchangable f…

### PR DESCRIPTION
**Pull request by dan-luk**
…ields

### CODE REVIEW

**Comment by lloydde** [comment]
@dan-luk please refresh patch.

**Comment by lloydde** [comment]
Merged as bacfae9.

**Comment by bahamat** [comment]
Why are unchangeable fields even visible?

**Comment by lloydde** [comment]
@bahamat is there one or more fields who's display does not add value?

**Comment by bahamat** [comment]
I haven't seen it in use yet, but I would expect that only modifiable fields are presented at create time, with anything else shown when viewing the object after it's been created.

**Comment by lloydde** [comment]
https://smartos.org/bugview/ADMINUI-2134 suggests the MTU being viewable (read only) at time of create may be expected. It's one more chance to communicate the underlying settings.

**Pull request closed without merging**
