### PR TITLE
ADMINUI-2208 adminui doesn't pass request id to all workflow requests

### PR DESCRIPTION
**Pull request by YZaicev**

### CODE REVIEW

**Comment by askfongjojo** [comment]
Hi @YZaicev, @dan-luk - There is a problem with the job status stuck in "Setting up" when it has failed or been canceled. Shouldn't it be something like this:
```
function getSetupStatus(req, server, callback) {
    if (!server.setup_state) {
        server.setup_state = server.setup ? 'succeeded' : 'running';
    }
    if (server.setup) {
        return callback(null, server);
    }
```

**Comment by dan-luk** [comment]
Hi @askfongjojo 

```setup_state``` field is created in this function, and the code seems to be correct, let's look at it together:

if job has failed or cancelled:
.setup is false
.setting_up is false

so .setup_state is taken below from job and so displayed

**Comment by askfongjojo** [comment]
Hi @YZaicev, @dan-luk 

Here are the attribute values for the various scenarios:

`cancelled`
"setup": false
"setting_up": true
"status": "unknown"

`running`, `failed`
"setup": false
"setting_up": true
"status": "running"

`completed`
"setup": true
"setting_up": false
"status": "running"

When "setup" is false, there is the logic to look up the latest setup job status and display it as the setup status.

Granted there is a bug in cnapi where failed/canceled setup is not reflected correctly. But let's not change the current behavior (which is at least what people are used to) until we've fixed cnapi. One improvement I can see is that it is querying job status without passing the "name" parameter which is an indexed field. Would you please add "name=server-setup-1.0.2" to the GET query so that it results in a workflow query like this:
sdc-workflow /jobs?server_uuid=564d7a3d-88f7-e3d0-2408-ced4c61e25f8\&name=server-setup-1.0.2

This way it is not trying to do the naming filtering in the javascript. The sort order doesn't look like is guaranteed or else we can also add "&limit=1" to remove the local date sorting as well. I'll check with pedro but for now let's assume it's not.

**Comment by askfongjojo** [comment]
Merged as 3215a5d.

**Pull request closed without merging**
